package com.example.demo.service;

import com.example.api.model.TagModel;  // generated by api-spec
import com.example.demo.exception.ResourceNotFoundException;
import com.example.demo.model.Tag;      // in model dir/JPA entity
import com.example.demo.repository.TagRepository;
import org.springframework.stereotype.Service;

import java.time.ZoneOffset;
import java.util.List;

@Service
public class TagService {
    private final TagRepository tagRepository;

    public TagService(TagRepository tagRepository) {
        this.tagRepository = tagRepository;
    }

    public List<TagModel> getAllTags() {
        return tagRepository.findAll()
                .stream()
                .map(this::toApiModel)
                .toList();
    }

    public TagModel getTagById(Long id) {
        Tag tag = tagRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Tag not found with id " + id));
        return toApiModel(tag);
    }

    public TagModel createTag(TagModel tagModel) {
        Tag entity = new Tag(tagModel.getTitle(), tagModel.getDescription());
        Tag saved = tagRepository.save(entity);
        return toApiModel(saved);
    }

    public TagModel updateTag(Long id, TagModel tagModel) {
        Tag existing = tagRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Tag not found with id " + id));

        existing.setTitle(tagModel.getTitle());
        existing.setDescription(tagModel.getDescription());

        Tag saved = tagRepository.save(existing);
        return toApiModel(saved);
    }

    public void deleteTag(Long id) {
        if (!tagRepository.existsById(id)) {
            throw new ResourceNotFoundException("Tag not found with id " + id);
        }
        tagRepository.deleteById(id);
    }

    private TagModel toApiModel(Tag tag) {
        TagModel model = new TagModel(tag.getTitle(), tag.getDescription());
        model.setId(tag.getId());
        model.setTitle(tag.getTitle());
        model.setDescription(tag.getDescription());
        model.setCreatedAt(tag.getCreatedAt().atOffset(ZoneOffset.UTC));
        model.setUpdatedAt(tag.getCreatedAt().atOffset(ZoneOffset.UTC));
        return model;
    }

    private Tag toEntity(TagModel tagModel) { return new Tag(tagModel.getTitle(), tagModel.getDescription());}
}
